spring:
  application:
    name: VocabAuth
  config:
    import: optional:application-dev.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SQL_URL}
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}

server:
  port: 8080
  frontend:
    url: http://localhost:3000


jwt:
  secret: ${JWT_SECRET}
  accessToken:
    ExpirationTime: ${JWT_ACCESS_EXPIRE}
  refreshToken:
    ExpirationTime: ${JWT_REFRESH_EXPIRE}

# Rate Limiting Configuration
resilience4j:
  ratelimiter:
    instances:
      auth-login:
        limit-for-period: 5
        limit-refresh-period: 60s
        timeout-duration: 0s
      auth-register:
        limit-for-period: 3
        limit-refresh-period: 60s
        timeout-duration: 0s
      auth-general:
        limit-for-period: 20
        limit-refresh-period: 60s
        timeout-duration: 0s